In [3]:
import numpy as np

In [6]:
a1 = np.array([3, 6, 2, 7])
a1, a1.shape, type(a1)

(array([3, 6, 2, 7]), (4,), numpy.ndarray)

In [10]:
a2 = np.array([[6, 3, 7],
               [1, 2, 8]])

a2.shape, a2.ndim, a2

((2, 3),
 2,
 array([[6, 3, 7],
        [1, 2, 8]]))

In [17]:

a3 = np.array([[6, 8],
               [2, 3],
               [8, 10]])

a3.shape, a3

((3, 2),
 array([[ 6,  8],
        [ 2,  3],
        [ 8, 10]]))

In [37]:
a2_zeros = np.zeros([2, 3], dtype=int)
a2_zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a2_ones = np.ones((2, 3), dtype=int)
a2_ones

In [56]:
a1 = np.arange(0, 10)
arr_evens = np.arange(0, 10, 2)

print(a1, arr_evens)

# a1_random = np.random.randint(0, 10, size=(3,))
# a1_random

[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]


In [58]:
# WAP to take a int input from user and create a 2d array filled with that input

np.full((2, 3), int(input()))

array([[5, 5, 5],
       [5, 5, 5]])

In [65]:
arr = np.linspace(0, 10, 5)
np.printoptions(precision=1)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Assignment
# Create a 2D array with ones on the diagonal and zeros elsewhere