In [1]:
import numpy as np

gen_1d_array = lambda: np.random.randint(1, 10, (3), dtype=int)
gen_2d_array = lambda: np.random.randint(1, 10, (2, 2), dtype=int)

In [6]:
a1 = np.array([3, 6, 2, 7])
a1, a1.shape, type(a1)

(array([3, 6, 2, 7]), (4,), numpy.ndarray)

In [10]:
a2 = np.array([[6, 3, 7],
               [1, 2, 8]])

a2.shape, a2.ndim, a2

((2, 3),
 2,
 array([[6, 3, 7],
        [1, 2, 8]]))

In [17]:

a3 = np.array([[6, 8],
               [2, 3],
               [8, 10]])

a3.shape, a3

((3, 2),
 array([[ 6,  8],
        [ 2,  3],
        [ 8, 10]]))

In [37]:
a2_zeros = np.zeros([2, 3], dtype=int)
a2_zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a2_ones = np.ones((2, 3), dtype=int)
a2_ones

In [56]:
a1 = np.arange(0, 10)
arr_evens = np.arange(0, 10, 2)

print(a1, arr_evens)

# a1_random = np.random.randint(0, 10, size=(3,))
# a1_random

[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]


In [58]:
# WAP to take a int input from user and create a 2d array filled with that input

np.full((2, 3), int(input()))

array([[5, 5, 5],
       [5, 5, 5]])

In [65]:
arr = np.linspace(0, 10, 5)
np.printoptions(precision=1)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
# Assignment
# Create a 2D array with ones on the diagonal and zeros elsewhere

np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
np.random.randint(1, 10, size=(2, 3), dtype=int)

array([[6, 0, 6],
       [7, 7, 0]])

In [19]:
# Create an array with random samples from a normal distribution
np.random.randn(2, 4)

array([[-0.01319091, -1.72665215,  0.4611599 , -0.83435135],
       [ 1.77146286,  0.39893318, -0.93998599, -1.27922092]])

In [20]:
# Create an array with random samples from a uniform distribution
np.random.rand(2, 3)

array([[0.50555185, 0.39269528, 0.46614625],
       [0.88890214, 0.60559517, 0.32321181]])

In [23]:
np.empty((2, 3))

array([[0.50555185, 0.39269528, 0.46614625],
       [0.88890214, 0.60559517, 0.32321181]])

#### Array Operations

In [34]:
a = np.array([2, 5, 3])
b = np.array([1, 8, 4])

In [35]:
a + b
a * b
a / b

array([2.   , 0.625, 0.75 ])

In [3]:
[a, b] = [gen_2d_array(), gen_2d_array()]

a + b, a - b, a / b, a * b

(array([[ 8,  9],
        [14,  9]]),
 array([[-6,  1],
        [-4,  7]]),
 array([[0.14285714, 1.25      ],
        [0.55555556, 8.        ]]),
 array([[ 7, 20],
        [45,  8]]))

In [46]:
np.sin(a)

array([[0.41211849, 0.98935825],
       [0.14112001, 0.98935825]])

In [47]:
np.floor(a), np.ceil(a)

(array([[9., 8.],
        [3., 8.]]),
 array([[9., 8.],
        [3., 8.]]))

In [48]:
# To calculate the scalar magnitude of an np array

np.linalg.norm(a)

14.7648230602334

In [53]:
a = np.array([3, 7, 4])

a.mean(), a.std()

(4.666666666666667, 1.699673171197595)

In [59]:
# WAP to create a 3d array and find the product of all the elements and print

arr_3d = np.array([[1, 3, 2],
                   [6, 4, 2],
                   [2, 8, 5]])
arr_3d.prod()

23040

In [2]:
# WAP to create a 2d array and give me the product of elements column wise

arr_2d = np.array([[1, 3, 2],
                   [6, 4, 2]])

# axis=0 refers to column operation, axis=1 refers to row
arr_2d.prod(axis=0), arr_2d.prod(axis=1)

(array([ 6, 12,  4]), array([ 6, 48]))

In [4]:
# WAP to create a 1d array and print the sum of all the elements

arr_1d = np.array([2, 5, 7])
arr_1d.sum()

14

In [12]:
# WAP to create 2 1d arrays and Concatenate two 1D NumPy arrays along the row axis



a = gen_1d_array()
b = gen_1d_array()

a, b, np.concatenate((a, b), axis=0) # axis is by default zero

(array([2, 4, 3]), array([4, 8, 1]), array([2, 4, 3, 4, 8, 1]))

In [13]:
# WAP a to create a 1d array and print the max and min element along their indices

a = gen_1d_array()
a, a.max(), a.min(), np.argmax(a)

(array([9, 2, 4]), 9, 2, 0)

In [34]:
# Assignment
# 1. Given a 2D NumPy array, flatten it into a 1D array

gen_2d_array = lambda: np.random.randint(1, 10, (2, 2), dtype=int)

a_2d = gen_2d_array()

a_2d, a_2d.flatten(), np.reshape(a_2d, np.size(a_2d))



(array([[8, 9],
        [2, 3]]),
 array([8, 9, 2, 3]),
 array([8, 9, 2, 3]))

In [36]:
# 2. Given a 1D NumPy array, reverse its elements
gen_1d_array = lambda: np.random.randint(1, 10, (3), dtype=int)

a_1d = gen_1d_array()

# a_1d, a_1d[::-1]
a_1d, np.flip(a_1d)

(array([6, 3, 1]), array([1, 3, 6]))

In [47]:
# Array Slicing

a = np.array([[2, 3, 5],
              [4, 7, 1],
              [8, 9, 5]])
              
a[:2] # First two rows
a[:, 2] # Third col (cols are 0-based)
a[2, 1] # Elem in third row and second col
a[:, 1] # All rows of the second col

array([5, 1, 5])

In [52]:
a = np.arange(12)
a.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
a = np.arange(2, 16)

a.reshape((2, 7))
a.reshape((7, 2))

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [60]:
b = np.arange(1, 7)
b.reshape((2, -1))  # -1 acts as a placeholder, and gives numpy the chance to figure out the right int in that position


array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
# 2. Reshape a 1D NumPy array into a 3D array with dimensions (2, 2, 3)

a = np.arange(1, 13)
a.reshape((2, 2, 3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
# Matrix Broadcasting

a = np.array([[1, 2, 3],
              [4, 5, 6]])

# x has to have a similar shape (in row or col) for broadcasting to work
x = np.array([[6],
              [7]])

a + x

array([[ 7,  8,  9],
       [11, 12, 13]])

In [96]:
# Practice Exercises

np.arange(0, 4).mean()

# Find the square of each element in a1 and print
s = np.arange(0, 4)
s**2  # OR np.square(a1)

# Perform element-wise multiplication between two NumPy arrays
a, b = np.random.randint(1, 5), np.random.randint(1, 3)
a * b

# Calculate the sum of the diagonal elements of a 3x3 matrix
a_3d = np.random.randint(1, 7, (3, 3), dtype=int)
np.trace(a_3d) # OR sum(np.diag(a_3d))

(array([[4, 2, 3],
        [1, 3, 5],
        [5, 3, 1]]),
 8)

In [ ]:
# Practice link: https://www.w3resource.com/python-exercises/numpy/numpy_100_exercises_with_solutions.php